# Generated by Django 5.2.17 on 2026-09-17 03:55

import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LoginAttempt",
            fields=[
                (
                    "key",
                    models.CharField(max_length=64, primary_key=True, serialize=False),
                ),
                ("failures", models.PositiveIntegerField(default=0)),
                ("since", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action", models.CharField(max_length=80)),
                ("target", models.CharField(max_length=200)),
                ("detail", models.CharField(blank=True, max_length=1000)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AuthorProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("must_change_password", models.BooleanField(default=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="author_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Mod",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "install_name",
                    models.CharField(max_length=100, unique=True, verbose_name="安装文件名"),
                ),
                ("title", models.CharField(max_length=100, verbose_name="作品名称")),
                ("summary", models.CharField(max_length=240, verbose_name="一句话介绍")),
                (
                    "description",
                    models.TextField(max_length=20000, verbose_name="详细说明"),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("基础功能", "基础功能"),
                            ("战斗与平衡", "战斗与平衡"),
                            ("起源与事件", "起源与事件"),
                            ("装备与外观", "装备与外观"),
                            ("汉化", "汉化"),
                            ("框架", "框架"),
                            ("其他", "其他"),
                        ],
                        default="基础功能",
                        max_length=20,
                        verbose_name="分类",
                    ),
                ),
                ("source_url", models.URLField(blank=True, verbose_name="原作或源码链接")),
                ("license", models.CharField(max_length=200, verbose_name="分发许可")),
                (
                    "game_version",
                    models.CharField(
                        default="1.5.2.3", max_length=80, verbose_name="适用游戏版本"
                    ),
                ),
                (
                    "dlc",
                    models.CharField(blank=True, max_length=300, verbose_name="所需 DLC"),
                ),
                (
                    "mod_ids",
                    models.TextField(
                        blank=True, max_length=2000, verbose_name="游戏内 MOD ID"
                    ),
                ),
                (
                    "requires",
                    models.TextField(
                        blank=True, max_length=2000, verbose_name="前置 MOD ID"
                    ),
                ),
                (
                    "conflicts",
                    models.TextField(
                        blank=True, max_length=2000, verbose_name="冲突 MOD ID"
                    ),
                ),
                (
                    "save_impact",
                    models.CharField(
                        choices=[
                            ("unknown", "尚未确认"),
                            ("no", "作者声明无影响"),
                            ("yes", "有影响，请阅读说明"),
                        ],
                        default="unknown",
                        max_length=10,
                        verbose_name="存档影响",
                    ),
                ),
                (
                    "seed_impact",
                    models.CharField(
                        choices=[
                            ("unknown", "尚未确认"),
                            ("no", "作者声明无影响"),
                            ("yes", "有影响，请阅读说明"),
                        ],
                        default="unknown",
                        max_length=10,
                        verbose_name="种子影响",
                    ),
                ),
                (
                    "compatibility_notes",
                    models.TextField(
                        blank=True, max_length=5000, verbose_name="兼容与安装说明"
                    ),
                ),
                ("blocked", models.BooleanField(default=False)),
                ("block_reason", models.CharField(blank=True, max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Release",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("version", models.CharField(max_length=40, verbose_name="版本号")),
                ("notes", models.TextField(max_length=10000, verbose_name="更新说明")),
                ("metadata", models.JSONField(default=dict)),
                ("archive", models.FileField(upload_to="archives/")),
                ("cover", models.FileField(blank=True, upload_to="covers/")),
                ("sha256", models.CharField(max_length=64)),
                ("size", models.PositiveBigIntegerField()),
                ("inspection", models.JSONField(default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "未公开"),
                            ("published", "已公开"),
                            ("withdrawn", "已撤回"),
                        ],
                        default="draft",
                        max_length=15,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                (
                    "mod",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="releases",
                        to="catalog.mod",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="mod",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("install_name"),
                name="unique_install_name_casefold",
            ),
        ),
        migrations.AddConstraint(
            model_name="release",
            constraint=models.UniqueConstraint(
                fields=("mod", "version"), name="unique_mod_version"
            ),
        ),
    ]
