# Generated by Django 5.2.17 on 2026-09-17 07:43

import catalog.storage
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DesktopRelease",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "version",
                    models.CharField(max_length=40, unique=True, verbose_name="版本号"),
                ),
                ("notes", models.TextField(max_length=10000, verbose_name="更新说明")),
                (
                    "file",
                    models.FileField(
                        storage=catalog.storage.DesktopStorage(),
                        upload_to="releases/",
                        verbose_name="Windows 程序",
                    ),
                ),
                ("sha256", models.CharField(max_length=64)),
                ("size", models.PositiveBigIntegerField()),
                ("prerelease", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "未公开"),
                            ("published", "已公开"),
                            ("withdrawn", "已撤回"),
                        ],
                        default="draft",
                        max_length=15,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
