# Generated by Django 5.2.17 on 2026-09-17 10:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0002_desktoprelease"),
    ]

    operations = [
        migrations.CreateModel(
            name="SeedUploadBudget",
            fields=[
                (
                    "key",
                    models.CharField(max_length=64, primary_key=True, serialize=False),
                ),
                ("count", models.PositiveIntegerField(default=0)),
                ("since", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name="SharedSeed",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("fingerprint", models.CharField(max_length=64, unique=True)),
                ("seed", models.CharField(db_index=True, max_length=10)),
                ("origin", models.CharField(db_index=True, max_length=50)),
                ("game_version", models.CharField(blank=True, max_length=30)),
                ("combat_difficulty", models.SmallIntegerField(blank=True, null=True)),
                (
                    "economic_difficulty",
                    models.SmallIntegerField(blank=True, null=True),
                ),
                ("budget_difficulty", models.SmallIntegerField(blank=True, null=True)),
                ("record", models.JSONField()),
                ("note", models.CharField(blank=True, max_length=1000)),
                (
                    "ports",
                    models.PositiveIntegerField(blank=True, db_index=True, null=True),
                ),
                (
                    "named",
                    models.PositiveIntegerField(blank=True, db_index=True, null=True),
                ),
                (
                    "melee",
                    models.SmallIntegerField(blank=True, db_index=True, null=True),
                ),
                ("blocked", models.BooleanField(db_index=True, default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="SharedSeedBrother",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("melee", models.SmallIntegerField(null=True)),
                ("ranged", models.SmallIntegerField(null=True)),
                ("defense", models.SmallIntegerField(null=True)),
                ("traits", models.CharField(blank=True, max_length=2000)),
                (
                    "seed",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="brothers",
                        to="catalog.sharedseed",
                    ),
                ),
            ],
        ),
    ]
