# Generated by Django 5.2.17 on 2026-09-17 11:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0003_seed_sharing"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteVisitor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token_hash", models.CharField(max_length=64, unique=True)),
                ("first_seen", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("last_seen", models.DateTimeField(db_index=True)),
                ("page_views", models.PositiveBigIntegerField(default=1)),
            ],
        ),
    ]
