# Generated by Django 5.2.17 on 2026-09-18 10:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0004_site_visitors"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SuggestionBudget",
            fields=[
                (
                    "key",
                    models.CharField(max_length=64, primary_key=True, serialize=False),
                ),
                ("count", models.PositiveIntegerField(default=0)),
                ("since", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name="Suggestion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("feature", "功能建议"),
                            ("bug", "问题反馈"),
                            ("other", "其他想法"),
                        ],
                        max_length=15,
                        verbose_name="建议类型",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="一句话概括")),
                ("details", models.TextField(max_length=5000, verbose_name="详细说明")),
                (
                    "version",
                    models.CharField(blank=True, max_length=60, verbose_name="相关版本"),
                ),
                (
                    "nickname",
                    models.CharField(blank=True, max_length=40, verbose_name="怎么称呼你"),
                ),
                (
                    "contact",
                    models.CharField(blank=True, max_length=150, verbose_name="联系方式"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "待查看"),
                            ("reviewing", "处理中"),
                            ("done", "已完成"),
                            ("closed", "暂不采纳"),
                        ],
                        db_index=True,
                        default="new",
                        max_length=15,
                        verbose_name="处理状态",
                    ),
                ),
                (
                    "internal_notes",
                    models.TextField(blank=True, max_length=5000, verbose_name="内部备注"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "handled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
    ]
