# Generated by Django 5.2.17 on 2026-09-28 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_profileuploadbudget_sharedmodfile_sharedprofile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestion',
            name='diagnostic_report',
            field=models.TextField(blank=True, default='', db_default='', max_length=60000, verbose_name='诊断报告'),
        ),
    ]
