# Generated by Django 5.2.17 on 2026-10-06 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_suggestion_diagnostic_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='release',
            name='sha256',
            field=models.CharField(db_index=True, max_length=64),
        ),
        migrations.AddIndex(
            model_name='release',
            index=models.Index(fields=['status', '-created_at'], name='release_status_created_idx'),
        ),
        migrations.AddIndex(
            model_name='sharedprofile',
            index=models.Index(fields=['blocked', '-created_at', '-id'], name='profile_public_created_idx'),
        ),
    ]
