const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const { JSDOM } = require(process.argv[2] ? path.resolve(process.argv[2]) : 'jsdom');
const root = path.resolve(__dirname, '..');
const catalog = JSON.parse(fs.readFileSync(path.join(root, 'localization/catalog.json'), 'utf8'));
const dom = new JSDOM('<body><button id="start">New Campaign</button><div id="nested"><b>Unknown name</b> <span>Load Campaign</span></div><input id="name" value="New Campaign"><div contenteditable="true">New Campaign</div><div id="counter">Day 12</div></body>', {runScripts:'outside-only'});
dom.window.BBMOD_DICTIONARY = Object.assign({}, ...Object.values(catalog.groups));
dom.window.eval(fs.readFileSync(path.join(root, 'localization/runtime.js'), 'utf8'));
dom.window.BBMODL10N.start();
const doc = dom.window.document;
assert.equal(doc.querySelector('#start').textContent, '新建战役');
assert.equal(doc.querySelector('#nested span').textContent, '读取战役');
assert.equal(doc.querySelector('#nested b').textContent, 'Unknown name');
assert.equal(doc.querySelector('#name').value, 'New Campaign');
assert.equal(doc.querySelector('[contenteditable]').textContent, 'New Campaign');
assert.equal(doc.querySelector('#counter').textContent, '第 12 天');
assert.equal(dom.window.BBMODL10N.translate('  New Campaign  '), '  新建战役  ');
assert.equal(dom.window.BBMODL10N.translate('new_campaign_id'), 'new_campaign_id');
assert.equal(dom.window.BBMODL10N.translate('天数1'), '第 1 天');
assert.equal(dom.window.BBMODL10N.translate('天数 12'), '第 12 天');
doc.querySelector('#counter').firstChild.nodeValue = 'Day 13';
const added = doc.createElement('div'); added.textContent = 'Save Campaign'; doc.body.appendChild(added);
setTimeout(() => {
    assert.equal(doc.querySelector('#counter').textContent, '第 13 天');
    assert.equal(added.textContent, '保存战役');
    assert(doc.querySelector('#start').className.includes('bbmod-l10n-text'));
    dom.window.close();
    console.log('PASS: display translation, dynamic updates, markup and input preservation');
}, 30);
